name: CMake on MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cd ${{github.workspace}}/silkcodec && cmake -B ${{github.workspace}}/silkcodec/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cd ${{github.workspace}}/silkcodec/build && cmake .. --config ${{env.BUILD_TYPE}}

    - name: Make
      run: cd ${{github.workspace}}/silkcodec/build && make
    
    - uses: actions/upload-artifact@v4
      with:
        name: libsilkcodec.dylib
        path: ${{github.workspace}}/silkcodec/build/libsilkcodec.dylib
