name: CMake on MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Make
      run: cd ${{github.workspace}}/build && make
    
    - uses: actions/upload-artifact@v4
      with:
        name: libsilkcodec.dylib
        path: ${{github.workspace}}/build/libsilkcodec.dylib
