name: Release
on:
  push:
    tags:
    - '*.*.*'
jobs:
  create_relese:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4

      - name: Build player
        run: |
          cd ${{github.workspace}}/SilkSharp.SilkPlayer && dotnet publish
      
      - name: Zipping All
        uses: vimtor/action-zip@v1.2
        with:
            files: SilkSharp.SilkPlayer/bin/Release/net8.0/publish/
            dest: SilkPlayer.zip

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            SilkPlayer.zip